version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_db
    restart: always
    ports:
      - "6333:6333"

  chatbot:
    build: .
    container_name: chatbot_app
    depends_on:
      - qdrant
    ports:
      - "8000:8000"
      - "8501:8501"
    environment:
      - QDRANT_HOST=http://qdrant:6333
